Updated nging-ctl
Support ssl generation (self signed and acme)
Support pre-existing ssl
Update site config

diff --git a/rootfs/scripts/bin/nginx-ctl b/rootfs/scripts/bin/nginx-ctl
--- a/rootfs/scripts/bin/nginx-ctl
+++ b/rootfs/scripts/bin/nginx-ctl
@@ -9,7 +9,12 @@ OPT_DEBUG=1
 OPT_PRIMARY_DOMAIN=
 OPT_DOMAINS=
 OPT_WITH_MODSECURITY=0
-OPT_SSL_MODE='auto'
+OPT_ENABLE_STUB_STATUS=0
+OPT_ENABLE_PING=0
+OPT_ENABLE_FAVEICO=0
+OPT_SSL_GENERATE=0
+OPT_SSL_TYPE='acme'
+OPT_USE_SSL=
 
 print_message() {
   local message_type=$1
@@ -98,8 +103,13 @@ usage() {
   echo "  add-site                        Add new site"
   echo "    Options:"
   echo "      -d, --domain <TLD>          The domain for which to create the site. If multiple domains are specified, then the first domain will be used as the primary domain"
-  echo "          --ssl-mode <SSL_MODE>   SSL Mode to be used, auto, none, acme, self"
+  echo "          --ssl-generate          Flag to enable ssl generation"
+  echo "          --ssl-type <ACME|SELF>  If ssl-generate is enabled then this must be set. Defines if acme ssl certificate is to be generated or self signed"
+  echo "          --use-ssl <SITE>        Use existing SSL certificate"
   echo "          --with-modsecurity      Enable modsecurity with default rules on this site"
+  echo "          --enable-stub-status    Enable nginx stub status. Will be available in /healthz"
+  echo "          --enable-ping           Enable ping pong location. Defaults to /ping"
+  echo "          --enable-faveico        Add faveicon patch - Prevent logging and 404 not found"
   echo
   echo "  list-sites                      List all sites"
   echo
@@ -142,8 +152,8 @@ usage() {
   echo "  ssl-generate                    Generate SSL certificate"
   echo "    Options:"
   echo "      -d, --domain <TLD>          The domain for which to create the SSL. If multiple domains are specified, then the first domain will be used as the primary domain"
-  echo "          --ssl-mode <SSL_MODE>   SSL Mode to be used, auto, none, acme, self. Defaults to auto"
-  echo "          --server <SERVER>       The server with which to register, default is letsencrypt"
+  echo "          --ssl-type <TYPE>       Can be self or acme. Defaults to acme"
+  echo "          --server <SERVER>       The server with which to register, default is letsencrypt. Required for ACME type"
   echo
   echo "  ssl-renew                       Renew certificate. If domain is not specified, then all certificates will be renewed"
   echo "    Options:"
@@ -186,7 +196,8 @@ command_initialize() {
   setgroup /etc/nginx
   setgroup /usr/local/nginx
 
-  for i in /app /templates ${MAXMIND_PATH} ${MODSEC_AUDIT_STORAGE} ${MODSEC_DATA_DIR} ${MODSEC_TMP_DIR} ${MODSEC_UPLOAD_DIR} ${NGINX_CACHE_DIR} ${NGINX_CERT_PATH} ${NGINX_LOG_PATH} /scripts 
+  # ${MODSEC_AUDIT_STORAGE} is inside nginx log path
+  for i in /app /templates ${MODSEC_DATA_DIR} ${MODSEC_TMP_DIR} ${MODSEC_UPLOAD_DIR} ${NGINX_CACHE_DIR} ${NGINX_LOG_PATH} 
   do
     if [ ! -d "${i}" ]
     then
@@ -383,36 +394,51 @@ command_list_sites() {
 }
 
 command_add_site() {
+  local SSL_REPLACE_NAME='$server_name'
   if [ "${OPT_PRIMARY_DOMAIN}" == "" ]; then
     ERROR "Atleast one value for domain must be passed"
   fi
   if [ -f ${NGINX_SITE_PATH}/${OPT_PRIMARY_DOMAIN}.conf ] || [ -f ${NGINX_SITE_PATH}/${OPT_PRIMARY_DOMAIN}.conf.disabled ]; then
     ERROR "Configutation for domain ${OPT_PRIMARY_DOMAIN} already exists!"
   fi
+  if [ "${OPT_USE_SSL}" != "" ]; then
+    SSL_REPLACE_NAME=OPT_USE_SSL
+  fi
+  if [ "${OPT_SSL_GENERATE}" == 1 ]; then
+    command_ssl_generate
+  fi
 
   # Lets create directories
   INFO "Creating directories:"
-  INFO "${NGINX_WEBROOT_PATH}/${OPT_PRIMARY_DOMAIN}         : The webroot for this domain"
-  mkdir -p ${NGINX_WEBROOT_PATH}/${OPT_PRIMARY_DOMAIN}
-  INFO "${NGINX_LOG_PATH}/${OPT_PRIMARY_DOMAIN}             : Logs path for this domain"
-  mkdir -p ${NGINX_LOG_PATH}/${OPT_PRIMARY_DOMAIN}
-  INFO "${NGINX_CERT_PATH}/${OPT_PRIMARY_DOMAIN}            : Path where certificates are stored"
-  mkdir -p ${NGINX_CERT_PATH}/${OPT_PRIMARY_DOMAIN}
-  INFO "${NGINX_CACHE_PATH}/${OPT_PRIMARY_DOMAIN}           : Cache path"
-  mkdir -p ${NGINX_CACHE_PATH}/${OPT_PRIMARY_DOMAIN}
+  INFO "Webroot                 : ${NGINX_WEBROOT_PATH}/${OPT_PRIMARY_DOMAIN}"
+  INFO "Logs                    : ${NGINX_LOG_PATH}/${OPT_PRIMARY_DOMAIN}"
+  INFO "Cache                   : ${NGINX_CACHE_PATH}/${OPT_PRIMARY_DOMAIN}"
+  mkdir -p ${NGINX_WEBROOT_PATH}/${OPT_PRIMARY_DOMAIN} ${NGINX_LOG_PATH}/${OPT_PRIMARY_DOMAIN} ${NGINX_CACHE_PATH}/${OPT_PRIMARY_DOMAIN}
 
   # Create the file
   export PRIMARY_DOMAIN=$OPT_PRIMARY_DOMAIN ALL_DOMAINS=$OPT_DOMAINS NGINX_CACHE_PATH=$NGINX_CACHE_PATH
   envsubst '$PRIMARY_DOMAIN, $ALL_DOMAINS, $NGINX_CACHE_PATH' < /templates/site.conf.template > ${NGINX_SITE_PATH}/${OPT_PRIMARY_DOMAIN}.conf
 
-  if [ -f ${NGINX_CERT_PATH}/${OPT_PRIMARY_DOMAIN}/certificate.key ] && [ -f ${NGINX_CERT_PATH}/${OPT_PRIMARY_DOMAIN}/certificate.crt ];
+  if [ -f ${NGINX_CERT_PATH}/${SSL_REPLACE_NAME}.key ] && [ -f ${NGINX_CERT_PATH}/${SSL_REPLACE_NAME}.crt ];
   then
     DEBUG "Updating config to enable ssl"
     sed -i 's|#listen 443 ssl;|listen 443 ssl;|' ${NGINX_SITE_PATH}/${OPT_PRIMARY_DOMAIN}.conf
     sed -i 's|#listen \[::\]:443 ssl;|listen [::]:443 ssl;|' ${NGINX_SITE_PATH}/${OPT_PRIMARY_DOMAIN}.conf
-    sed -i 's|#ssl_certificate /etc/nginx/certs/$primary_domain/certificate.crt;|ssl_certificate /etc/nginx/certs/$primary_domain/certificate.crt;|' ${NGINX_SITE_PATH}/${OPT_PRIMARY_DOMAIN}.conf
-    sed -i 's|#ssl_certificate_key /etc/nginx/certs/$primary_domain/certificate.key;|ssl_certificate_key /etc/nginx/certs/$primary_domain/certificate.key;|' ${NGINX_SITE_PATH}/${OPT_PRIMARY_DOMAIN}.conf
+    sed -i 's|#ssl_certificate /etc/nginx/certs/$server_name.crt;|ssl_certificate /etc/nginx/certs/'"${SSL_REPLACE_NAME}"'.crt;|' ${NGINX_SITE_PATH}/${OPT_PRIMARY_DOMAIN}.conf
+    sed -i 's|#ssl_certificate_key /etc/nginx/certs/$server_name.key;|ssl_certificate_key /etc/nginx/certs/'"${SSL_REPLACE_NAME}"'.key;|' ${NGINX_SITE_PATH}/${OPT_PRIMARY_DOMAIN}.conf
     sed -i 's|#include /etc/nginx/conf.d/ssl-config.conf;|include /etc/nginx/conf.d/ssl-config.conf;|' ${NGINX_SITE_PATH}/${OPT_PRIMARY_DOMAIN}.conf
+  fi
+  if [ "${OPT_ENABLE_STUB_STATUS}" == 1 ]; then
+    DEBUG "Updating config to enable ssl"
+    sed -i 's|#include /etc/nginx/conf.d/default-location-healthz.conf;|include /etc/nginx/conf.d/default-location-healthz.conf;|' ${NGINX_SITE_PATH}/${OPT_PRIMARY_DOMAIN}.conf
+  fi
+  if [ "${OPT_ENABLE_PING}" == 1 ]; then
+    DEBUG "Updating config to enable ssl"
+    sed -i 's|#include /etc/nginx/conf.d/default-location-ping;|include /etc/nginx/conf.d/default-location-ping.conf;|' ${NGINX_SITE_PATH}/${OPT_PRIMARY_DOMAIN}.conf
+  fi
+  if [ "${OPT_ENABLE_FAVEICO}" == 1 ]; then
+    DEBUG "Updating config to enable ssl"
+    sed -i 's|#include /etc/nginx/conf.d/default-location-faveico.conf;|include /etc/nginx/conf.d/default-location-faveico.conf;|' ${NGINX_SITE_PATH}/${OPT_PRIMARY_DOMAIN}.conf
   fi
   
   if [ "$OPT_WITH_MODSECURITY" == 1 ]; then
@@ -421,10 +447,10 @@ command_add_site() {
   fi
 
   INFO "Ensuring right permissions are present"
-  setgroup ${NGINX_WEBROOT_PATH}/${OPT_PRIMARY_DOMAIN} 
-  setgroup ${NGINX_LOG_PATH}/${OPT_PRIMARY_DOMAIN} 
-  setgroup ${NGINX_CERT_PATH}/${OPT_PRIMARY_DOMAIN} 
-  setgroup ${NGINX_CACHE_PATH}/${OPT_PRIMARY_DOMAIN} 
+  setgroup ${NGINX_WEBROOT_PATH}/${OPT_PRIMARY_DOMAIN}
+  setgroup ${NGINX_LOG_PATH}/${OPT_PRIMARY_DOMAIN}
+  setgroup ${NGINX_CERT_PATH}/${OPT_PRIMARY_DOMAIN}*
+  setgroup ${NGINX_CACHE_PATH}/${OPT_PRIMARY_DOMAIN}
   setgroup ${NGINX_SITE_PATH}/${OPT_PRIMARY_DOMAIN}.conf
   
   # if ! nginx -t; then
@@ -685,12 +711,108 @@ command_acme_register(){
   fi
 }
 
-command_ssl_generate() {
-  echo "Not Implemented"
+move_certificates() {
+  local SRC_CRT_FILE=$1
+  local SRC_KEY_FILE=$2
+  local DST_CRT_FILE=$3
+  local DST_KEY_FILE=$4
+  DEBUG "Moving certificate and key files"
+  DEBUG "SOURCE CERTIFICATE               : ${SRC_CRT_FILE}"
+  DEBUG "SOURCE KEY                       : ${SRC_KEY_FILE}"
+  DEBUG "DESTINATION CERTIFICATE          : ${DST_CRT_FILE}"
+  DEBUG "DESTINATION KEY                  : ${DST_KEY_FILE}"
+  # Check if cert already exists if so backup and move
+  if [ -f $DST_KEY_FILE ]; then
+    DEBUG "Backing up old certificate"
+    mv $DST_CRT_FILE $DST_CRT_FILE.$(date +%Y-%m-%d)
+  fi
+  if [ -f $DST_KEY_FILE ]; then
+  DEBUG "Backing up old key"
+    mv $DST_KEY_FILE $DST_KEY_FILE.$(date +%Y-%m-%d)
+  fi
+  # Move
+  DEBUG "Moving certificate & key"
+  cp -f $SRC_CRT_FILE $DST_CRT_FILE
+  cp -f $SRC_KEY_FILE $DST_KEY_FILE
+  # Permissions
+  DEBUG "Setting permissions"
+  setgroup $DST_CRT_FILE $DST_KEY_FILE
 }
 
-command_ssl_renew() {
-  echo "Not implemented"
+command_ssl_generate() {
+  if [ "${OPT_PRIMARY_DOMAIN}" == "" ]; then
+    ERROR "Atleast one value for domain must be passed"
+  fi
+  INFO "SSL Options passed:"
+  INFO "Primary Domain                : ${OPT_PRIMARY_DOMAIN}"
+  INFO "All Domains (incl primary)    : ${OPT_DOMAINS}"
+  INFO "SSL Type                      : ${OPT_SSL_TYPE}"
+  INFO "Certificate File              : ${NGINX_CERT_PATH}/${OPT_PRIMARY_DOMAIN}.crt"
+  INFO "Key File                      : ${NGINX_CERT_PATH}/${OPT_PRIMARY_DOMAIN}.crt"
+  local SRC_CRT_FILE=
+  local SRC_KEY_FILE=
+  local DST_CRT_FILE=${NGINX_CERT_PATH}/${OPT_PRIMARY_DOMAIN}.crt
+  local DST_KEY_FILE=${NGINX_CERT_PATH}/${OPT_PRIMARY_DOMAIN}.key
+  case $OPT_SSL_TYPE in
+    "acme")
+      debug "Generating SSL certificate using ACME for ${OPT_DOMAINS}"
+      # local COMMAND="--issue --stateless -d ${ALL_DOMAINS// /-d }"
+      # debug "command: ${COMMAND}"
+      callAcme --issue --stateless -d ${ALL_DOMAINS// /-d}
+      SRC_CRT_FILE=${ACME_HOME}/${OPT_PRIMARY_DOMAIN}_ecc/fullchain.cer
+      SRC_KEY_FILE=${ACME_HOME}/${OPT_PRIMARY_DOMAIN}_ecc/fullchain.key
+      ;;
+    "self")
+      DEBUG "Generating self signed certificate from ${OPT_DOMAINS}"
+      openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
+          -addext "subjectAltName=DNS:${OPT_DOMAINS// /,DNS:}" \
+          -keyout "/tmp/$OPT_PRIMARY_DOMAIN.key" \
+          -out "/tmp/$OPT_PRIMARY_DOMAIN.crt" \
+          -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=$OPT_PRIMARY_DOMAIN"
+      SRC_CRT_FILE="/tmp/$OPT_PRIMARY_DOMAIN.crt"
+      SRC_KEY_FILE="/tmp/$OPT_PRIMARY_DOMAIN.key"
+      ;;
+    *)
+      echo "Invalid SSL mode: $MODE"
+      exit 1
+      ;;
+  esac
+  move_certificates $SRC_CRT_FILE $SRC_KEY_FILE $DST_CRT_FILE $DST_KEY_FILE
+  command_reload
+}
+
+command_acme_renew() {
+  callAcme --renew
+  # Copy all files which have changed
+  local BACKUP_DATE=$(date +%Y-%m-%d)
+  for dir in $ACME_CERT_PATH; do
+    if [ -d $DIR ]; then
+      local DOMAIN=${DIR//_ecc/}
+      if ! cmp -s "$file1" "$file2"; then
+        INFO "Certificate for ${DOMAIN} has changed. Migrating"
+        move_certificates $DIR/fullchain.cer $DIR/$DOMAIN.key ${NGINX_CERT_PATH}/$DOMAIN.crt ${NGINX_CERT_PATH}/$DOMAIN.key
+      fi
+    fi
+  done;
+  command_reload
+}
+
+command_acme_remove() {
+  callAcme --remove -d ${OPT_PRIMARY_DOMAIN}
+  rm -f ${ACME_HOME}/${OPT_PRIMARY_DOMAIN}
+  rm -f ${ACME_HOME}/${OPT_PRIMARY_DOMAIN}_ecc
+  # Remove in nginx
+  local BACKUP_DATE=$(date +%Y-%m-%d)
+  mv -f ${NGINX_CERT_PATH}/${OPT_PRIMARY_DOMAIN}.crt ${NGINX_CERT_PATH}/${OPT_PRIMARY_DOMAIN}.crt.$BACKUP_DATE
+  mv -f ${NGINX_CERT_PATH}/${OPT_PRIMARY_DOMAIN}.key ${NGINX_CERT_PATH}/${OPT_PRIMARY_DOMAIN}.key.$BACKUP_DATE
+  # Disable SSL in site config
+  DEBUG "Updating config to enable ssl"
+  sed -i 's|listen 443 ssl;|#listen 443 ssl;|' ${NGINX_SITE_PATH}/${OPT_PRIMARY_DOMAIN}.conf
+  sed -i 's|listen \[::\]:443 ssl;|#listen [::]:443 ssl;|' ${NGINX_SITE_PATH}/${OPT_PRIMARY_DOMAIN}.conf
+  sed -i 's|ssl_certificate /etc/nginx/certs/$primary_domain/certificate.crt;|#ssl_certificate /etc/nginx/certs/$server_name.crt;|' ${NGINX_SITE_PATH}/${OPT_PRIMARY_DOMAIN}.conf
+  sed -i 's|ssl_certificate_key /etc/nginx/certs/$primary_domain/certificate.key;|#ssl_certificate_key /etc/nginx/certs/$server_name.key;|' ${NGINX_SITE_PATH}/${OPT_PRIMARY_DOMAIN}.conf
+  sed -i 's|include /etc/nginx/conf.d/ssl-config.conf;|#include /etc/nginx/conf.d/ssl-config.conf;|' ${NGINX_SITE_PATH}/${OPT_PRIMARY_DOMAIN}.conf
+  command_reload
 }
 
 # Maxmind GeoIP database management
@@ -750,7 +872,7 @@ if ! command -v "command_${COMMAND}" > /dev/null 2>&1; then
 fi
 shift
 
-if ! args="$(getopt -o hs:e:d:o: --long help,server:,email:,domain:,key:,edition:,database:,with-modsecurity,ssl-mode:,debug -n "$ARG0" -- "$@")"; then
+if ! args="$(getopt -o hs:e:d:o: --long help,server:,email:,domain:,key:,edition:,database:,with-modsecurity,enable-stub-status,enable-ping,enable-faveico,ssl-generate,ssl-type:,use-ssl:,debug -n "$ARG0" -- "$@")"; then
   usage
   exit 1
 fi
@@ -775,8 +897,10 @@ while [ "$#" -gt 0 ]; do
     -d | --domain)
       if [ -z "${OPT_PRIMARY_DOMAIN}" ]; then
         OPT_PRIMARY_DOMAIN=${1//\'/}
+        OPT_DOMAINS="${1//\'/}"
+      else
+        OPT_DOMAINS="${OPT_DOMAINS} ${1//\'/}"
       fi
-      OPT_DOMAINS="${OPT_DOMAINS} ${1//\'/}"
       shift
       ;;
     --key)
@@ -794,8 +918,24 @@ while [ "$#" -gt 0 ]; do
     --with-modsecurity)
       OPT_WITH_MODSECURITY=1
       ;;
-    --ssl-mode)
-      OPT_SSL_MODE=$(echo "${1//\'/}" | tr '[:upper:]' '[:lower:]')
+    --enable-stub-status)
+      OPT_ENABLE_STUB_STATUS=1
+      ;;
+    --enable-ping)
+      OPT_ENABLE_PING=1
+      ;;
+    --enable-faveico)
+      OPT_ENABLE_FAVEICO=1
+      ;;
+    --ssl-generate)
+      OPT_SSL_GENERATE=1
+      ;;
+    --ssl-type)
+      OPT_SSL_TYPE=$(echo "${1//\'/}" | tr '[:upper:]' '[:lower:]')
+      shift
+      ;;
+    --use-ssl)
+      OPT_USE_SSL=$(echo "${1//\'/}" | tr '[:upper:]' '[:lower:]')
       shift
       ;;
     --debug)
@@ -811,8 +951,20 @@ while [ "$#" -gt 0 ]; do
   esac
 done
 
-if [ "${OPT_SSL_MODE}" != "auto" ] && [ "${OPT_SSL_MODE}" != "acme" ] && [ "${OPT_SSL_MODE}" != "none" ] && [ "${OPT_SSL_MODE}" != "manual" ] && [ "${OPT_SSL_MODE}" != "self" ]; then
-  ERROR "Invalid SSL Mode ${OPT_SSL_MODE}. Allowed values are auto. acme, none, manual and self"
+# if [ "${OPT_SSL_MODE}" != "auto" ] && [ "${OPT_SSL_MODE}" != "acme" ] && [ "${OPT_SSL_MODE}" != "none" ] && [ "${OPT_SSL_MODE}" != "manual" ] && [ "${OPT_SSL_MODE}" != "self" ]; then
+#   ERROR "Invalid SSL Mode ${OPT_SSL_MODE}. Allowed values are auto. acme, none, manual and self"
+# fi
+if [ "${OPT_SSL_TYPE}" != "acme" ] && [ "${OPT_SSL_TYPE}" != "self" ]; then
+  ERROR "SSL Type must be either acme or self."
+fi
+
+if [ "${OPT_USE_SSL}" != "" ]; then
+  # Check if ssl exists for domain
+  if [ ! -f ${NGINX_CERT_PATH}/${OPT_USE_SSL}.crt ] !! [ ! -f ${NGINX_CERT_PATH}/${OPT_USE_SSL}.key ]; then
+    ERROR "Ensure SSL Certificate is present for ${OPT_USE_SSL} in path ${NGINX_CERT_PATH}.\n Also ensure the extension for certificate is .crt and for key is .key"
+  fi
+  # SSL Type will be ignored
+  OPT_SSL_GENERATE=0
 fi
 
 if [ "${OPT_ACME_SERVER}" != "letsencrypt" ] && [ "${OPT_ACME_SERVER}" != "zerossl" ]; then
